<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-07 02:32
=======
# Generated by Django 6.0.5 on 2026-05-27 01:57
>>>>>>> f8dba96501fb03a42c59f7c82ad17de050d38c26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=200)),
=======
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
>>>>>>> f8dba96501fb03a42c59f7c82ad17de050d38c26
            ],
        ),
    ]
