# Generated by Django 6.0.5 on 2026-05-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_completemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
